name: Generate GitHub Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *" # daily at 00:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: SOHAILASGHARWORKOFFICIAL
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=%2338bdf8&color_dots=%230b1c36,%23112f55,%231b4d80,%23256fb0,%2338bdf8
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=%2338bdf8&color_dots=%23061529,%230b2a4a,%23134470,%23216ca3,%2338bdf8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to output branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
          force_orphan: true
          commit_message: "chore: update contribution snake"
